name: Release bat

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  cicd:
    uses: ./.github/workflows/CICD.yml

  publish:
    needs: cicd
    environment:
      name: crates.io
      url: https://crates.io/crates/bat
    runs-on: ubuntu-latest
    permissions:
      contents: write # For git push of the tag.
    steps:
      - uses: actions/checkout@v4

      # Figure out what tag to use
      - name: calculate version
        id: version
        run: |
          version=$(cargo read-manifest --manifest-path Cargo.toml | jq --raw-output .version)
          echo "GIT_TAG=v${version}" >> $GITHUB_OUTPUT

      # Try to cargo publish bat.
      - run: cargo publish -p cargo-public-api
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

      # cargo publish succeeded. Push a git tag corresponding to the published version.
      - name: push tag
        run: |
          git tag ${{ steps.version.outputs.GIT_TAG }}
          git push origin ${{ steps.version.outputs.GIT_TAG }}

  release:
    needs: publish
    runs-on: ubuntu-latest
    permissions:
      contents: write # So we can create a release.
    steps:
      - uses: actions/checkout@v4
      - name: calculate version
        id: version
        run: |
          version=$(cargo read-manifest --manifest-path Cargo.toml | jq --raw-output .version)
          echo "VERSION=${version}" >> $GITHUB_OUTPUT
          echo "GIT_TAG=v${version}" >> $GITHUB_OUTPUT
      - run: cargo install parse-changelog@0.6.4 --locked
      - name: create release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          notes="$(parse-changelog CHANGELOG.md ${{ steps.version.outputs.VERSION }})"
          title="${{ steps.version.outputs.GIT_TAG }}"
          gh release create --title "$title" --notes "$notes" ${{ steps.version.outputs.GIT_TAG }}
